package com.zapateria.inventario.model.enums;

public enum Categoria {
    ZAPATILLA, BOTA, SANDALIA, ZAPATO_VESTIR, DEPORTIVO, OTRO,
    URBANO, ZUECO, MOCASIN, CHINELA, BORCEGO, CARTERA, BILLETERA,
    ZAPATILLA_CASUAL, NAUTICO, COMFORT, OUTDOOR, COLEGIAL, ZAPATO
}
